const express = require('express');
const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 8080;

// Middleware
app.use(express.json());

// Load axe-core from node_modules
const axeCoreSource = fs.readFileSync(
        path.join(__dirname, 'node_modules', 'axe-core', 'axe.min.js'),
        'utf8'
    );

// Health check endpoint
app.get('/health', (req, res) => {
        res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});

// Main page
app.get('/', (req, res) => {
        res.send(`
        <!DOCTYPE html>
        <html>
        <head>
            <title>SentryPrime Enterprise Scanner</title>
                <style>
                        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
                                .header { text-align: center; margin-bottom: 40px; }
                                        .scan-form { background: #f5f5f5; padding: 30px; border-radius: 8px; }
                                                input[type="url"] { width: 100%; padding: 12px; margin: 10px 0; border: 1px solid #ddd; border-radius: 4px; }
                                                        button { background: #007cba; color: white; padding: 12px 24px; border: none; border-radius: 4px; cursor: pointer; }
                                                                button:hover { background: #005a87; }
                                                                        .results { margin-top: 30px; padding: 20px; background: white; border-radius: 8px; }
                                                                            </style>
                                                                            </head>
                                                                            <body>
                                                                                <div class="header">
                                                                                        <h1>🛡️ SentryPrime Enterprise</h1>
                                                                                                <p>Professional Accessibility Scanner powered by Puppeteer + axe-core</p>
                                                                                                    </div>
                                                                                                        
                                                                                                            <div class="scan-form">
                                                                                                                    <h2>Scan Website for Accessibility Issues</h2>
                                                                                                                            <form id="scanForm">
                                                                                                                                        <input type="url" id="urlInput" placeholder="Enter website URL (e.g., https://example.com)" required>
                                                                                                                                                    <button type="submit">🔍 Start Accessibility Scan</button>
                                                                                                                                                            </form>
                                                                                                                                                                </div>
                                                                                                                                                                    
                                                                                                                                                                        <div id="results" class="results" style="display:none;">
                                                                                                                                                                                <h3>Scan Results</h3>
                                                                                                                                                                                        <div id="resultsContent"></div>
                                                                                                                                                                                            </div>
                                                                                                                                                                                                
                                                                                                                                                                                                    <script>
                                                                                                                                                                                                            document.getElementById('scanForm').addEventListener('submit', async (e) => {
                                                                                                                                                                                                                        e.preventDefault();
                                                                                                                                                                                                                                    const url = document.getElementById('urlInput').value;
                                                                                                                                                                                                                                                const resultsDiv = document.getElementById('results');
                                                                                                                                                                                                                                                            const resultsContent = document.getElementById('resultsContent');
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                    resultsContent.innerHTML = '<p>🔄 Scanning... This may take a few moments.</p>';
                                                                                                                                                                                                                                                                                                resultsDiv.style.display = 'block';
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                        const response = await fetch('/api/scan', {
                                                                                                                                                                                                                                                                                                                                                            method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({ url: url })
                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const result = await response.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (result.success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const violations = result.data.violations;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resultsContent.innerHTML = \`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h4>✅ Scan Complete!</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p><strong>URL:</strong> \${result.data.url}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p><strong>Score:</strong> \${result.data.score}/100</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p><strong>Issues Found:</strong> \${violations.length}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p><strong>Scan Time:</strong> \${result.data.scanTime}ms</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \${violations.length > 0 ? 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<h4>Issues:</h4>' + violations.map(v => 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        \`<div style="border-left: 4px solid #ff6b6b; padding: 10px; margin: 10px 0; background: #fff5f5;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong>\${v.impact.toUpperCase()}:</strong> \${v.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <br><small>Elements affected: \${v.nodes}</small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>\`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ).join('') : 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<p style="color: green;">🎉 No accessibility issues found!</p>'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    \`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        resultsContent.innerHTML = \`<p style="color: red;">❌ Error: \${result.error}</p>\`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resultsContent.innerHTML = \`<p style="color: red;">❌ Network error: \${error.message}</p>\`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `);
});

// Scan endpoint
app.post('/api/scan', async (req, res) => {
        const startTime = Date.now();
        let browser = null;

             try {
                         const { url } = req.body;

            if (!url) {
                            return res.status(400).json({
                                                success: false,
                                                error: 'URL is required'
                            });
            }

            let targetUrl = url;
                         if (!targetUrl.startsWith('http://') && !targetUrl.startsWith('https://')) {
                                         targetUrl = 'https://' + targetUrl;
                         }

console.log(`Starting accessibility scan for: ${targetUrl}`);

                            // Launch Puppeteer with Google Cloud Run optimized settings
                                    browser = await puppeteer.launch({
                                                headless: 'new',
                                                            executablePath: '/usr/bin/google-chrome-stable',
                                                                        args: [
                                                                                        '--no-sandbox',
                                                                                                        '--disable-setuid-sandbox',
                                                                                                                        '--disable-dev-shm-usage',
                                                                                                                                        '--disable-accelerated-2d-canvas',
                                                                                                                                                        '--no-first-run',
                                                                                                                                                                        '--no-zygote',
                                                                                                                                                                                        '--single-process',
                                                                                                                                                                                                        '--disable-gpu',
                                                                                                                                                                                                                        '--disable-web-security',
                                                                                                                                                                                                                                        '--disable-features=VizDisplayCompositor'
                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                timeout: 30000
                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        const page = await browser.newPage();
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                        // Set viewport
                                                                                                                                                                                                                                                                                                               
